version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3
    steps:
      - checkout
      - run: 
          command: bundle install
      - run: 
          command: bundle exec rails test
